name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # @link https://github.com/php-actions/composer
      - uses: php-actions/composer@v5
        with:
          php_version: 7.1
          version: 1

      # @link https://github.com/php-actions/example-phpunit
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          php_version: 7.4
          php_extensions: xdebug
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text
        env:
          XDEBUG_MODE: coverage
