name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - uses: actions/checkout@v2
      - uses: FranzDiebold/github-env-vars-action@v1.2.0

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      # @link https://docs.codeclimate.com/docs/configuring-test-coverage
      - name: Code climage (before)
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          export GIT_COMMIT_SHA="$Env:CI_SHA"
          echo "GIT_COMMIT_SHA=$GIT_COMMIT_SHA"
          export GIT_BRANCH="$Env:CI_ACTION_REF_NAME_SLUG"
          echo "GIT_BRANCH=$GIT_BRANCH"
          ./cc-test-reporter before-build

      # @link https://github.com/php-actions/composer
      - uses: php-actions/composer@v5
        with:
          php_version: 7.4
          php_extensions: mbstring iconv json xdebug
          version: 1

      # @link https://github.com/php-actions/example-phpunit
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          php_version: 7.4
          php_extensions: mbstring iconv json xdebug
          bootstrap: test/bootstrap.php
          configuration: phpunit.xml
          args: --coverage-clover ./build/logs/clover.xml
        env:
          XDEBUG_MODE: coverage

      - name: Code climage (after)
        run: |
           export GIT_COMMIT_SHA="$Env:CI_SHA"
           echo "GIT_COMMIT_SHA=$GIT_COMMIT_SHA"
           export GIT_BRANCH="$Env:CI_ACTION_REF_NAME_SLUG"
           echo "GIT_BRANCH=$GIT_BRANCH"
           ./cc-test-reporter after-build -t clover --debug
